[package]
name = "apriori_tid"
version = "0.1.0"
edition = "2024"

[dependencies]
apriori = { path = "../apriori" }
parallel = { path = "../parallel" }
ahash = "0.8.12"
[dev-dependencies]
tester = { path = "../tester" }
