name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
defaults:
  run:
    shell: bash
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependency
      run: sudo apt-get update && sudo apt-get install -y libopenmpi-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Parallel Examples
      run: |
        cargo install --force cargo-mpirun
        ci/run-examples.sh